name: chillfix_provider
description: Service provider app to connect with customers seeking household services

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1 # State management
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  google_fonts: ^4.0.4
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5

  flutter_localizations: # Added for localization
    sdk: flutter
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/default_profile.png
    - assets/icons/chillfix_logo.png
    - assets/fonts/Poppins-Regular.ttf

  fonts:
    - family: Poppins # Added for design consistency
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
